In [38]:
import numpy as np

In [3]:
l1=range(10000)
l2=range(10000)

a1=np.arange(1000)
a2=np.arange(1000)

In [4]:
import time
s1= time.time()
for i,j in zip(l1,l1):
    l1+l2
print("python took time :",(time.time()-s1)*10000)

TypeError: unsupported operand type(s) for +: 'range' and 'range'

In [5]:
s2 = time.time()
a1+a2
print("numpy took time: ",(time.time()-s2)*1000)




numpy took time:  0.31375885009765625


In [6]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
np.array([[1,2,3,4], [5,6,7,8]], dtype="complex")
np.array([[1,2,3,4],[5,6,7,8]], dtype="float")

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [8]:
arr1 =np.array([[1,2,3,4,],[4,5,6,7]])
arr1.sum()
arr.sum(axis=1) 
arr.sum(axis=0)

NameError: name 'arr' is not defined

In [9]:
arr1.max()
arr1.min()
arr1.max(axis=0) 

array([4, 5, 6, 7])

In [10]:
arr1.ravel()

array([1, 2, 3, 4, 4, 5, 6, 7])

In [11]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.__version__

'1.17.2'

In [13]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
x = np.array([1,2])
print(x.dtype)

int64


In [15]:
x =np.array([[1,2],[3,4]],dtype=np.float64)
print(x.dtype)

float64


In [16]:
x=np.arange(10)
c = 0
for i in x:
    if (i%2 == 1):
        print(i)
        c +=0
        

1
3
5
7
9


In [17]:
x = np.arange(10)
for i in x:
    x[i%2 == 1]=-1
    print(x)

[0 1 2 3 4 5 6 7 8 9]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]


In [18]:
for i in np.nditer(x):
    print(i)

-1
-1
-1
-1
-1
-1
-1
-1
-1
-1


In [19]:
a2 = np.arange(10).reshape(5,2)
a2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [20]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [21]:
x=np.arange(10)
out=np.where(x%2==1,-1,x)  #where is used to inplace of
print(x)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [22]:
a=np.arange(10).reshape(5,2)  #concatenate of array vertically 
b=np.repeat(1,10).reshape(5,2)
print(a)
print(b)
print(np.concatenate([a,b],axis=1))  
print(np.hstack([a,b]))  #write same things using hstack


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
[[0 1 1 1]
 [2 3 1 1]
 [4 5 1 1]
 [6 7 1 1]
 [8 9 1 1]]
[[0 1 1 1]
 [2 3 1 1]
 [4 5 1 1]
 [6 7 1 1]
 [8 9 1 1]]


In [23]:
a = np.array([1,2,3])
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [24]:
a=np.array([1,2,3,2,3,4,3,4,5,6])  #intersection and union of two array
b=np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))
print(np.union1d(a,b))

    

[2 4]
[ 1  2  3  4  5  6  7  8  9 10]


In [25]:
s =set()
for i in a:
    if i in b:
        s.add(i)
print(np.array(list(s)))    
        

[2 4]


In [26]:
s = set()
for i in a:
    if i in b:
        print(i)

2
2
4
4


In [27]:
list=[]
for i,jin 

SyntaxError: invalid syntax (<ipython-input-27-b193b84283ec>, line 2)

In [28]:
a=np.array([1,2,3,4,5])   #difference of 2 ARRAY
b=np.array([5,6,7,8,9]) 
print(np.setdiff1d(a,b))

[1 2 3 4]


In [29]:
l=[]
for i in a:
    if i not in b :
        l.append(i)
print(l)

[1, 2, 3, 4]


In [30]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a,b)
print("we have to find out matching position")

ValueError: either both or neither of x and y should be given

In [33]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [35]:
print(arr[[1,0,2], :]) #swap rows

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [36]:
print(arr[:,[1,0,2]]) #swap columns 

[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [41]:
import random   #using random number

np.random.randn(2,3)

array([[-0.37720403, -1.66605431,  1.61307724],
       [-1.21320947,  0.28969604, -0.51598492]])

In [42]:
np.random.randint(4,6) #it provide number between 4 to 6

5

In [45]:
np.random.randint(4,6, 4) #it provide number  between 4 to 6 --4 times 

array([5, 5, 5, 4])

In [47]:
np.random.randint(2,4)

2

In [48]:
arr = np.arange(20)

In [60]:
np.random.choice(arr)  #it will print any number of array within array

13

In [54]:
np.random.shuffle(arr)

In [57]:
arr

array([17, 18,  2,  3,  5,  7, 10,  6, 13,  9, 16,  4, 12,  1, 11, 15,  0,
        8, 14, 19])

In [58]:
np.random.permutation(arr) #it will print array of their permutation but if arr write seperated 

array([ 4,  1,  9, 14, 12, 13,  2,  3,  0, 16,  7, 17, 15, 18, 10, 11, 19,
        5,  8,  6])

In [61]:
arr #print arr

array([17, 18,  2,  3,  5,  7, 10,  6, 13,  9, 16,  4, 12,  1, 11, 15,  0,
        8, 14, 19])

In [64]:
arr1 = np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [66]:
np.random.shuffle(arr1)  
arr1   #shuffle columns

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])